apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

# kubectl create secret generic mssql-secret --from-literal=SA_PASSWORD="M9Str0ngPa55w0rd123!" 